// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sha256_top_HH_
#define _sha256_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sha256_final.h"
#include "sha256_transform.h"
#include "sha256_top_ctx_inbkb.h"

namespace ap_rtl {

struct sha256_top : public sc_module {
    // Port declarations 17
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<5> > data_address0;
    sc_out< sc_logic > data_ce0;
    sc_in< sc_lv<8> > data_q0;
    sc_out< sc_lv<5> > hash_address0;
    sc_out< sc_logic > hash_ce0;
    sc_out< sc_logic > hash_we0;
    sc_out< sc_lv<8> > hash_d0;
    sc_out< sc_lv<5> > hash_address1;
    sc_out< sc_logic > hash_ce1;
    sc_out< sc_logic > hash_we1;
    sc_out< sc_lv<8> > hash_d1;


    // Module declarations
    sha256_top(sc_module_name name);
    SC_HAS_PROCESS(sha256_top);

    ~sha256_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sha256_top_ctx_inbkb* ctx_in_data_U;
    sha256_final* grp_sha256_final_fu_112;
    sha256_transform* grp_sha256_transform_fu_144;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > ctx_datalen;
    sc_signal< sc_lv<32> > ctx_bitlen_0;
    sc_signal< sc_lv<32> > ctx_bitlen_1;
    sc_signal< sc_lv<32> > ctx_state_0;
    sc_signal< sc_lv<32> > ctx_state_1;
    sc_signal< sc_lv<32> > ctx_state_2;
    sc_signal< sc_lv<32> > ctx_state_3;
    sc_signal< sc_lv<32> > ctx_state_4;
    sc_signal< sc_lv<32> > ctx_state_5;
    sc_signal< sc_lv<32> > ctx_state_6;
    sc_signal< sc_lv<32> > ctx_state_7;
    sc_signal< sc_lv<6> > ctx_in_data_address0;
    sc_signal< sc_logic > ctx_in_data_ce0;
    sc_signal< sc_logic > ctx_in_data_we0;
    sc_signal< sc_lv<8> > ctx_in_data_d0;
    sc_signal< sc_lv<8> > ctx_in_data_q0;
    sc_signal< sc_lv<6> > ctx_in_data_address1;
    sc_signal< sc_logic > ctx_in_data_ce1;
    sc_signal< sc_logic > ctx_in_data_we1;
    sc_signal< sc_lv<8> > ctx_in_data_q1;
    sc_signal< sc_lv<6> > i_fu_245_p2;
    sc_signal< sc_lv<6> > i_reg_315;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > exitcond_i_fu_239_p2;
    sc_signal< sc_lv<1> > tmp_1_i_fu_268_p2;
    sc_signal< sc_lv<1> > tmp_1_i_reg_325;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ap_start;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ap_done;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ap_idle;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ap_ready;
    sc_signal< sc_lv<5> > grp_sha256_final_fu_112_final_hash_address0;
    sc_signal< sc_logic > grp_sha256_final_fu_112_final_hash_ce0;
    sc_signal< sc_logic > grp_sha256_final_fu_112_final_hash_we0;
    sc_signal< sc_lv<8> > grp_sha256_final_fu_112_final_hash_d0;
    sc_signal< sc_lv<5> > grp_sha256_final_fu_112_final_hash_address1;
    sc_signal< sc_logic > grp_sha256_final_fu_112_final_hash_ce1;
    sc_signal< sc_logic > grp_sha256_final_fu_112_final_hash_we1;
    sc_signal< sc_lv<8> > grp_sha256_final_fu_112_final_hash_d1;
    sc_signal< sc_lv<6> > grp_sha256_final_fu_112_ctx_in_data_address0;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_in_data_ce0;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_in_data_we0;
    sc_signal< sc_lv<8> > grp_sha256_final_fu_112_ctx_in_data_d0;
    sc_signal< sc_lv<6> > grp_sha256_final_fu_112_ctx_in_data_address1;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_in_data_ce1;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_in_data_we1;
    sc_signal< sc_lv<8> > grp_sha256_final_fu_112_ctx_in_data_d1;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_state_0_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_state_0_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_state_1_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_state_1_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_state_2_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_state_2_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_state_3_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_state_3_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_state_4_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_state_4_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_state_5_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_state_5_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_state_6_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_state_6_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_state_7_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_state_7_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_bitlen_0_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_bitlen_0_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_final_fu_112_ctx_bitlen_1_o;
    sc_signal< sc_logic > grp_sha256_final_fu_112_ctx_bitlen_1_o_ap_vld;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ap_start;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ap_done;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ap_idle;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ap_ready;
    sc_signal< sc_lv<6> > grp_sha256_transform_fu_144_data_transform_address0;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_data_transform_ce0;
    sc_signal< sc_lv<6> > grp_sha256_transform_fu_144_data_transform_address1;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_data_transform_ce1;
    sc_signal< sc_lv<32> > grp_sha256_transform_fu_144_ctx_state_0_o;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ctx_state_0_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_transform_fu_144_ctx_state_1_o;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ctx_state_1_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_transform_fu_144_ctx_state_2_o;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ctx_state_2_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_transform_fu_144_ctx_state_3_o;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ctx_state_3_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_transform_fu_144_ctx_state_4_o;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ctx_state_4_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_transform_fu_144_ctx_state_5_o;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ctx_state_5_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_transform_fu_144_ctx_state_6_o;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ctx_state_6_o_ap_vld;
    sc_signal< sc_lv<32> > grp_sha256_transform_fu_144_ctx_state_7_o;
    sc_signal< sc_logic > grp_sha256_transform_fu_144_ctx_state_7_o_ap_vld;
    sc_signal< sc_lv<6> > i_i_reg_101;
    sc_signal< sc_lv<1> > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_reg_grp_sha256_final_fu_112_ap_start;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_reg_grp_sha256_transform_fu_144_ap_start;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > i_i_cast1_fu_234_p1;
    sc_signal< sc_lv<32> > ctx_datalen_assign_i_fu_256_p2;
    sc_signal< sc_lv<32> > tmp_4_i_fu_300_p2;
    sc_signal< sc_lv<32> > tmp_3_i_fu_288_p2;
    sc_signal< sc_lv<1> > tmp_2_i_fu_278_p2;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_6A09E667;
    static const sc_lv<32> ap_const_lv32_BB67AE85;
    static const sc_lv<32> ap_const_lv32_3C6EF372;
    static const sc_lv<32> ap_const_lv32_A54FF53A;
    static const sc_lv<32> ap_const_lv32_510E527F;
    static const sc_lv<32> ap_const_lv32_9B05688C;
    static const sc_lv<32> ap_const_lv32_1F83D9AB;
    static const sc_lv<32> ap_const_lv32_5BE0CD19;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<32> ap_const_lv32_40;
    static const sc_lv<32> ap_const_lv32_FFFFFDFF;
    static const sc_lv<32> ap_const_lv32_200;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ctx_datalen_assign_i_fu_256_p2();
    void thread_ctx_in_data_address0();
    void thread_ctx_in_data_address1();
    void thread_ctx_in_data_ce0();
    void thread_ctx_in_data_ce1();
    void thread_ctx_in_data_d0();
    void thread_ctx_in_data_we0();
    void thread_ctx_in_data_we1();
    void thread_data_address0();
    void thread_data_ce0();
    void thread_exitcond_i_fu_239_p2();
    void thread_grp_sha256_final_fu_112_ap_start();
    void thread_grp_sha256_transform_fu_144_ap_start();
    void thread_hash_address0();
    void thread_hash_address1();
    void thread_hash_ce0();
    void thread_hash_ce1();
    void thread_hash_d0();
    void thread_hash_d1();
    void thread_hash_we0();
    void thread_hash_we1();
    void thread_i_fu_245_p2();
    void thread_i_i_cast1_fu_234_p1();
    void thread_tmp_1_i_fu_268_p2();
    void thread_tmp_2_i_fu_278_p2();
    void thread_tmp_3_i_fu_288_p2();
    void thread_tmp_4_i_fu_300_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
